version: '3'
services:
  nginx:
    container_name: app_nginx
    image: nginx
    ports:
      - "8090:80"
    networks:
      - app_network
    volumes:
      - ./app:/var/www/app
      - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  app_network: